# config for coco dataset
dataset: "coco"

# input/output/model paths
data_root: "./COCO2014"
data_name_list: "./data/coco/val_id.txt"
output_path: "./output/classification/coco"
clip_path: "/data2/wjl/sdsseg/open_vocabulary/clip-vit-large-patch14"
blip_path: "/data/wjl/ptp_diffusion/blip/blip-image-captioning-large"

# classification process settings (classification.py)
clip_device: "cuda:5"
blip_device: "cuda:5"
num_workers: 0
pin_mem: True
input_size: 224
enable_text_similarity: True
enable_text_and_image_similarity: True
enable_synonym_matching: True
train_interpolation: "bicubic"
text_threshold: 0.8
text_and_image_threshold: 0.97

# dataset metainfo
labels_synonym:
    {
        "person":
            [
                "person",
                "they",
                "he",
                "she",
                "him",
                "her",
                "man",
                "woman",
                "child",
                "baby",
                "skateboarder",
                "speaker",
                "boy",
                "girl",
                "bride",
                "groom",
                "parent",
                "couple",
                "people",
                "player",
                "wrestler",
                "snowboarder",
                "chef",
                "skier",
            ],
        "bicycle": ["bicycle"],
        "car":
            ["car", "jeep", "suv", "chrysler", "cooper", "van", "taxi", "cab"],
        "motorbike": ["motorbike", "scooter", "moped"],
        "aeroplane":
            ["aeroplane", "plane", "airplane", "jet", "jetliner", "shuttle"],
        "bus": ["bus", "tram"],
        "train": ["train"],
        "truck": ["truck", "van"],
        "boat": ["boat", "sailboat", "ship", "kayak", "canoe"],
        "traffic light": ["traffic light", "stoplight"],
        "fire hydrant": ["fire hydrant", "hydrant"],
        "stop sign": ["stop sign"],
        "parking meter": ["parking meter"],
        "bench": ["bench"],
        "bird":
            [
                "bird",
                "rooster",
                "hummingbird",
                "seagull",
                "parrot",
                "owl",
                "pigeon",
                "flamingo",
                "emu",
                "penguin",
                "duck",
                "eagle",
                "ostrich",
                "peacock",
                "pelican",
                "swan",
                "chicken",
            ],
        "cat": ["cat", "kitten", "lynx"],
        "dog": ["dog", "dachshund", "puppy", "pug"],
        "horse": ["horse", "pony"],
        "sheep": ["sheep", "lamb", "goat"],
        "cow": ["cow", "bull", "bison", "cattle"],
        "elephant": ["elephant"],
        "bear": ["bear"],
        "zebra": ["zebra"],
        "giraffe": ["giraffe"],
        "backpack": ["backpack"],
        "umbrella": ["umbrella"],
        "handbag": ["handbag"],
        "tie": ["tie"],
        "suitcase": ["suitcase", "luggage"],
        "frisbee": ["frisbee"],
        "skis": ["skis"],
        "snowboard": ["snowboard"],
        "sports ball": ["sports ball"],
        "kite": ["kite"],
        "baseball bat": ["baseball bat"],
        "baseball glove": ["baseball glove"],
        "skateboard": ["skateboard"],
        "surfboard": ["surfboard"],
        "tennis racket": ["tennis racket"],
        "bottle": ["bottle"],
        "wine glass": ["wine glass"],
        "cup": ["cup"],
        "fork": ["fork"],
        "knife": ["knife"],
        "spoon": ["spoon"],
        "bowl": ["bowl"],
        "banana": ["banana"],
        "apple": ["apple"],
        "sandwich": ["sandwich"],
        "orange": ["orange", "orange"],
        "broccoli": ["broccoli"],
        "carrot": ["carrot"],
        "hot dog": ["hot dog"],
        "pizza": ["pizza"],
        "donut": ["donut"],
        "cake": ["cake"],
        "chair": ["chair", "stool"],
        "sofa": ["sofa"],
        "pottedplant": ["pottedplant"],
        "bed": ["bed"],
        "diningtable": ["diningtable"],
        "toilet": ["toilet", "restroom"],
        "tvmonitor": ["tvmonitor", "television", "tv", "monitor"],
        "laptop": ["laptop"],
        "mouse": ["mouse"],
        "remote": ["remote", "control"],
        "keyboard": ["keyboard"],
        "cell phone": ["cell phone", "phone"],
        "microwave": ["microwave"],
        "oven": ["oven", "stove"],
        "toaster": ["toaster"],
        "sink": ["sink"],
        "refrigerator": ["refrigerator"],
        "book": ["book"],
        "clock": ["clock"],
        "vase": ["vase"],
        "scissors": ["scissors", "scissor"],
        "teddy bear": ["teddy bear"],
        "hair drier": ["hair drier"],
        "toothbrus": ["toothbrus", "toothbrush"],
    }
