# config for coco dataset
dataset: "coco"

# input/output/model paths
data_root: "./COCO2014"
data_name_list: "./data/coco/train_id.txt"
output_path: "./output/segmentation/coco"
diffusion_path: "/data/wjl/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/c9ab35ff5f2c362e9e22fbafe278077e196057f0"
blip_path: "/data/wjl/ptp_diffusion/blip/blip-image-captioning-large"

# main process settings (main.py)
dtype: 'fp16'
device: 4
seed: 4307
use_blip: True
print_prompt: False # 是否打印prompt
self_times: 1 # 乘以self_att的次数
self_64_times: 1 # 乘以self_64的次数

# ptp attention settings (ptp_utils.py)
# For stable diffusion v1.5 series, cross/self attns are both 16 layers in unet.
# As img pass down->mid->up unet block, img resolution will pass 64*2->32*2->16*2->8->16*3->32*3->64*3.
# Only part of attn layers have strong semantic information(https://arxiv.org/abs/2309.04109).
# So we can choose some layers to achieve better performance.
target_factor: 0.5 # source img latent需要融合target img latent的比例
valid_cross_layer: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # 需要选择的cross attention层
cross_weight: [1, 1, 1, 1, 10, 10, 15, 10, 10, 10, 1, 1, 1, 1, 1, 1] # 每一层cross attention的权重，列表长度需要和valid_cross_attn一致
valid_self_layer: [0, 1, 13, 14, 15] # 需要选择的self attention层
self_weight: [1, 1, 1, 1, 1] # 每一层self attention的权重，列表长度需要和valid_self_attn一致

# dds loss settings (dds_utils.py)
use_dds: True
timesteps: [1, 25, 50, 75, 100, 125, 150]
guidance_scale: 7.5
lr: 1.0e-1
loss_factor: 2000.0
alpha_exp: 0.0
sigma_exp: 0.0

# dataset metainfo
category:
  [
    "person",
    "bicycle",
    "car",
    "motorbike",
    "aeroplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "sofa",
    "pottedplant",
    "bed",
    "diningtable",
    "toilet",
    "tvmonitor",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrus",
  ]
bg_category:
  [
    "ground",
    "land",
    "grass",
    "tree",
    "building",
    "wall",
    "sky",
    "lake",
    "water",
    "river",
    "sea",
    "railway",
    "railroad",
    "helmet",
    "cloud",
    "house",
    "mountain",
    "ocean",
    "road",
    "rock",
    "street",
    "valley",
    "bridge",
  ]
