# pretrained model checkpoints
clip_model_path : '/data2/wjl/sdsseg/open_vocabulary/clip-vit-large-patch14'
blip_model_path : '/data/wjl/ptp_diffusion/blip/blip-image-captioning-large'
clip_device : 'cuda:5'
blip_device : 'cuda:5'
# dataset parameters
output_path : '/data2/wjl/ddsseg/data/voc10'
img_list : '/data2/wjl/ddsseg/data/voc10/voc10_val_id.txt'
data_path : '/data/wjl/data/VOCdevkit/VOC2010'
data_set : 'VOC10seg'
label_file_path : '/data2/wjl/ddsseg/data/voc10/voc10_cls_label.npy'
# method parameters
enable_text_similarity : True
enable_text_and_image_similarity : True
enable_synonym_matching : True
# algorithm parameters
input_size : 224
num_workers : 0
pin_mem : True
train_interpolation : 'bicubic'
nb_classes : 0
text_threshold : 0.8
text_and_image_threshold : 0.97

labels_synonym : {
    'airplane': ['airplane', 'plane', 'aeroplane', 'jet', 'jetliner', 'shuttle'],
    'bag': ['bag'],
    'bed': ['bed'],
    'bedclothes': ['bedclothes'],
    'bench': ['bench'],
    'bicycle': ['bicycle'],
    'bird': ['bird', 'rooster', 'hummingbird', 'seagull', 'parrot', 'owl', 'pigeon', 'flamingo', 'emu', 'penguin', 'duck', 'eagle', 'ostrich', 'peacock', 'pelican', 'chicken'],
    'boat': ['boat', 'sailboat', 'ship', 'kayak', 'canoe'],
    'book': ['book'],
    'bottle': ['bottle'],
    'building': ['building'],
    'bus': ['bus', 'tram'],
    'cabinet': ['cabinet'],
    'car': ['car', 'van', 'jeep', 'suv', 'chrysler', 'cooper', 'taxi', 'cab'],
    'cat': ['cat', 'kitten', 'lynx'],
    'ceiling': ['ceiling'],
    'chair': ['chair', 'stool'],
    'cloth': ['cloth'],
    'computer': ['computer'],
    'cow': ['cow', 'bull', 'bison', 'cattle'],
    'cup': ['cup'],
    'curtain': ['curtain'],
    'dog': ['dog', 'dachshund', 'puppy', 'pug'],
    'door': ['door'],
    'fence': ['fence'],
    'floor': ['floor'],
    'flower': ['flower'],
    'food': ['food', 'pizza', 'pepperoni'],
    'grass': ['grass'],
    'ground': ['ground'],
    'horse': ['horse', 'pony'],
    'keyboard': ['keyboard'],
    'light': ['light'],
    'motorbike': ['motorbike', 'scooter', 'moped'],
    'mountain': ['mountain'],
    'mouse': ['mouse'],
    'person': ['person', 'people', 'they', 'he', 'she', 'him', 'her', 'man', 'woman', 'child', 'baby', 'skateboarder', 'speaker', 'boy', 'girl', 'bride', 'groom', 'parent', 'couple', 'player', 'wrestler', 'chef', 'skier'],
    'plate': ['plate'],
    'platform': ['platform'],
    'plant': ['plant'],
    'road': ['road'],
    'rock': ['rock'],
    'sheep': ['sheep', 'lamb', 'goat'],
    'shelves': ['shelves'],
    'sidewalk': ['sidewalk'],
    'sign': ['sign'],
    'sky': ['sky'],
    'snow': ['snow'],
    'sofa': ['sofa'],
    'table': ['table'],
    'track': ['track'],
    'train': ['train'],
    'tree': ['tree'],
    'truck': ['truck'],
    'monitor': ['monitor', 'screen', 'tvmonitor', 'television', 'tv'],
    'wall': ['wall'],
    'water': ['water'],
    'window': ['window'],
    'wood': ['wood']
}
