name: elbo-t2ialign
channels:
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - compel==2.1.1
      - diffusers==0.33.1
      - einops==0.8.1
      - numpy==2.0.2
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - pillow==11.1.0
      - spacy==3.8.5
      - tqdm==4.67.1
      - transformers==4.51.3
      - accelerate==1.7.0
      - scikit-learn==1.6.1
      - joblib==1.4.2
      - safetensors==0.5.3
      - diskcache==5.6.3
      - simplecrf==0.2.1.1
      - pandas==2.2.3
      - itables==2.3.0
      - matplotlib==3.10.1
      - huggingface-hub==0.31.2
      - protobuf==5.29.2
      - sentencepiece==0.2.0
      - bitsandbytes==0.45.0
      - openai==1.71.0
      - python-box==7.3.0
