name: elbo-t2ialign
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pytorch=2.5.1
  - pip:
      - compel==2.0.3
      - diffusers==0.32.2
      - einops==0.8.0
      - numpy==2.0.2
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - pillow==11.0.0
      - spacy==3.8.4
      - tqdm==4.67.1
      - transformers==4.48.1
      - accelerate==1.3.0
      - scikit-learn==1.6.0
      - joblib==1.4.2
      - safetensors==0.4.5
      - diskcache==5.6.3
      - simplecrf==0.2.1.1
      - pandas==2.2.3
      - itables==2.2.4
      - matplotlib==3.10.0
      - torchvision==0.20.1
      - huggingface-hub==0.27.1
      - protobuf==5.29.2
      - sentencepiece==0.2.0
      - bitsandbytes==0.45.0
      - openai==1.60.0
      - python-box==7.3.0
      - clean-fid==0.1.35
