name: ddsseg
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.2
  - pytorch=2.5.0
  - pip:
      - compel==2.0.2
      - diffusers==0.30.3
      - einops==0.8.0
      - numpy==2.0.2
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - pillow==10.4.0
      - spacy==3.8.2
      - tqdm==4.66.5
      - transformers==4.45.1
      - accelerate==0.34.2
      - scikit-learn==1.5.2
      - joblib==1.4.2
      - safetensors==0.4.5
      - diskcache==5.6.3
      - simplecrf==0.2.1.1
      - pandas==2.2.3
      - itables==2.2.2
      - matplotlib==3.9.2
      - torchvision==0.20.0
