# generation process settings (generation_with_elbo.py)
infer_timesteps: 50
elbo_timesteps: 50
elbo_strength: 1.2
num_imgs_per_prompt: 1
num_prompts: 1000
non_entity_keywords:
  - group
  - bunch
  - lot
  - piece
  - part
  - kind
  - sort
  - type
  - category
  - set
  - stack
  - pile
  - collection
  - series
  - array
  - batch
  - range
  - pair
  - couple
  - portion
  - class
  - form
  - member
  - middle
  - edge
  - corner
  - side
  - center
  - end
  - top
  - bottom
  - surface
  - front
  - back
  - area
  - section
  - region
  - zone
  - field
  - space
  - boundary
  - line
  - layer
  - time
  - moment
  - period
  - phase
  - era
  - duration
  - stage
  - age
  - interval
  - point
  - second
  - minute
  - hour
  - day
  - amount
  - quantity
  - number
  - total
  - sum
  - level
  - degree
  - majority
  - minority
  - plenty
  - few
  - several
  - many
  - much
  - idea
  - concept
  - notion
  - thought
  - plan
  - system
  - process
  - method
  - way
  - approach
  - strategy
  - technique
  - style
  - rule
  - principle
  - aspect
  - factor
  - condition
  - state
  - case
  - example
  - instance
  - thing
  - stuff
  - item
  - object
  - activity
  - task
  - project
  - event
  - action
  - behavior
  - option
  - choice
  - possibility
  - result
  - outcome
  - effect
  - issue
  - problem
  - solution
  - question
  - answer
  - reason
  - cause
  - purpose
  - goal
  - aim
  - target
  - cluster
  - network
  - subgroup
  - segment
  - fraction
  - component
  - module
  - element
  - unit
  - block
  - part
  - section
  - chapter
  - row
  - column
  - list
  - table
  - chart
  - diagram
  - graph
  - data
  - information
  - evidence
  - result
  - statistic
  - figure
  - record
  - detail
  - value
  - metric
  - parameter
  - variable
  - factor
  - trend
  - estimate
  - calculation
  - measurement
  - observation
  - report
  - analysis
  - summary
