# metainfo for coco dataset
dataset: "coco"
data_root: "./datasets/coco_stuff164k"
data_name_list: "./data/coco/val_id.txt"
name_to_cls_labels: "./data/coco/cls_labels.npy"
img_path: "{data_root}/images/val2017/{img_name}.jpg"
gt_path: "{data_root}/annotations/val2017/{img_name}_labelTrainIds.png"
# we follow mmsegmentation to prepare dataset.
# so categories in coco dataset are the same with mmsegmentation.
# related code: https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/datasets/coco_stuff.py
# Besides, follow GroupViT (CVPR 2022), we only use first 80 classes in coco dataset.
# paper: https://arxiv.org/abs/2202.11094
# related code: https://github.com/NVlabs/GroupViT
num_cls: 80 # not including background
category:
  person:
    [
      "they",
      "he",
      "skateboarder",
      "couple",
      "woman",
      "snowboarder",
      "player",
      "she",
      "wrestler",
      "man",
      "him",
      "skier",
      "her",
      "chef",
      "girl",
      "boy",
      "parent",
      "person",
      "baby",
      "child",
      "groom",
      "bride",
      "people",
      "speaker",
    ]
  bicycle: ["bicycle", "bike"]
  car: ["cab", "taxi", "van", "jeep", "cooper", "chrysler", "car", "suv"]
  motorbike: ["motorbike", "motorcycle", "moped", "scooter"]
  aeroplane: ["jet", "jetliner", "shuttle", "airplane", "plane", "aeroplane"]
  bus: ["bus", "tram"]
  train: ["train", "high-speed train", "locomotive"]
  truck: ["truck", "van"]
  boat: ["ship", "kayak", "boat", "canoe", "sailboat"]
  traffic light: ["stoplight", "traffic light"]
  fire hydrant: ["fire hydrant", "hydrant"]
  stop sign: ["stop sign"]
  parking meter: ["parking meter"]
  bench: ["bench"]
  bird:
    [
      "hummingbird",
      "ostrich",
      "duck",
      "peacock",
      "bird",
      "seagull",
      "penguin",
      "swan",
      "owl",
      "rooster",
      "flamingo",
      "eagle",
      "pelican",
      "emu",
      "pigeon",
      "chicken",
      "parrot",
    ]
  cat: ["lynx", "kitten", "cat"]
  dog: ["dog", "puppy", "dachshund", "pug"]
  horse: ["pony", "horse"]
  sheep: ["lamb", "goat", "sheep"]
  cow: ["bison", "cattle", "bull", "cow"]
  elephant: ["elephant"]
  bear: ["bear"]
  zebra: ["zebra"]
  giraffe: ["giraffe"]
  backpack: ["backpack"]
  umbrella: ["umbrella"]
  handbag: ["handbag"]
  tie: ["tie"]
  suitcase: ["suitcase", "luggage"]
  frisbee: ["frisbee"]
  skis: ["skis"]
  snowboard: ["snowboard"]
  sports ball: ["sports ball"]
  kite: ["kite"]
  baseball bat: ["baseball bat"]
  baseball glove: ["baseball glove"]
  skateboard: ["skateboard"]
  surfboard: ["surfboard"]
  tennis racket: ["tennis racket"]
  bottle: ["bottle"]
  wine glass: ["wine glass"]
  cup: ["cup"]
  fork: ["fork"]
  knife: ["knife"]
  spoon: ["spoon"]
  bowl: ["bowl"]
  banana: ["banana"]
  apple: ["apple"]
  sandwich: ["sandwich"]
  orange: ["orange"]
  broccoli: ["broccoli"]
  carrot: ["carrot"]
  hot dog: ["hot dog"]
  pizza: ["pizza"]
  donut: ["donut"]
  cake: ["cake"]
  chair: ["stool", "chair"]
  sofa: ["couch", "sofa"]
  pottedplant: ["pottedplant", "potted plant"]
  bed: ["bed"]
  diningtable: ["dining table", "diningtable"]
  toilet: ["restroom", "toilet"]
  tvmonitor: ["tv", "television", "tvmonitor", "monitor"]
  laptop: ["laptop"]
  mouse: ["mouse"]
  remote: ["remote", "control"]
  keyboard: ["keyboard"]
  cell phone: ["cell phone", "phone"]
  microwave: ["microwave"]
  oven: ["stove", "oven"]
  toaster: ["toaster"]
  sink: ["sink"]
  refrigerator: ["refrigerator"]
  book: ["book"]
  clock: ["clock"]
  vase: ["vase"]
  scissors: ["scissors", "scissor"]
  teddy bear: ["teddy bear"]
  hair drier: ["hair drier"]
  toothbrus: ["toothbrus", "toothbrush"]
bg_category:
  [
    "ground",
    "land",
    "grass",
    "tree",
    "building",
    "wall",
    "sky",
    "lake",
    "water",
    "river",
    "sea",
    "railway",
    "railroad",
    "helmet",
    "cloud",
    "house",
    "mountain",
    "ocean",
    "road",
    "rock",
    "street",
    "valley",
    "bridge",
  ]
