# metainfo for context dataset
dataset: "context"
data_root: "./datasets/VOCdevkit/VOC2010"
data_name_list: "./data/context/val_id.txt"
name_to_cls_labels: "./data/context/cls_labels.npy"
img_path: "{data_root}/JPEGImages/{img_name}.jpg"
gt_path: "{data_root}/SegmentationClassContext/{img_name}.png"
# we follow mmsegmentation to prepare dataset.
# so categories in pascal context dataset are the same with mmsegmentation.
# related code: https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/datasets/pascal_context.py
num_cls: 59 # not including background
category:
  airplane: ["jet", "jetliner", "shuttle", "airplane", "plane", "aeroplane"]
  bag: ["bag"]
  bed: ["bed"]
  bedclothes: ["bedclothes", "bedclothing"]
  bench: ["bench"]
  bicycle: ["bicycle"]
  bird:
    [
      "hummingbird",
      "ostrich",
      "duck",
      "peacock",
      "bird",
      "seagull",
      "penguin",
      "owl",
      "rooster",
      "flamingo",
      "eagle",
      "pelican",
      "emu",
      "pigeon",
      "chicken",
      "parrot",
    ]
  boat: ["ship", "kayak", "boat", "canoe", "sailboat"]
  book: ["book"]
  bottle: ["bottle"]
  building: ["building"]
  bus: ["bus", "tram"]
  cabinet: ["cabinet"]
  car: ["cab", "taxi", "van", "jeep", "cooper", "chrysler", "car", "suv"]
  cat: ["lynx", "kitten", "cat"]
  ceiling: ["ceiling"]
  chair: ["stool", "chair"]
  cloth: ["cloth"]
  computer: ["computer"]
  cow: ["bison", "cattle", "bull", "cow"]
  cup: ["cup"]
  curtain: ["curtain"]
  dog: ["dog", "puppy", "dachshund", "pug"]
  door: ["door"]
  fence: ["fence"]
  floor: ["floor"]
  flower: ["flower"]
  food: ["food", "pizza", "pepperoni"]
  grass: ["grass"]
  ground: ["ground"]
  horse: ["pony", "horse"]
  keyboard: ["keyboard"]
  light: ["light"]
  motorbike: ["motorbike", "moped", "scooter"]
  mountain: ["mountain"]
  mouse: ["mouse"]
  person:
    [
      "they",
      "he",
      "skateboarder",
      "couple",
      "woman",
      "player",
      "she",
      "wrestler",
      "man",
      "him",
      "skier",
      "her",
      "chef",
      "girl",
      "boy",
      "parent",
      "person",
      "baby",
      "child",
      "groom",
      "people",
      "bride",
      "speaker",
    ]
  plate: ["plate"]
  platform: ["platform"]
  plant: ["potted plant", "pottedplant", "plant"]
  road: ["road"]
  rock: ["rock"]
  sheep: ["lamb", "goat", "sheep"]
  shelves: ["shelves"]
  sidewalk: ["sidewalk"]
  sign: ["sign"]
  sky: ["sky"]
  snow: ["snow"]
  sofa: ["sofa"]
  table: ["table"]
  track: ["track"]
  train: ["train"]
  tree: ["tree"]
  truck: ["truck"]
  monitor: ["television", "tvmonitor", "screen", "tv", "monitor"]
  wall: ["wall"]
  water: ["water"]
  window: ["window"]
  wood: ["wood"]
# TODO: construct PASCAL Context bg_category
bg_category:
  [
    "lake",
    "river",
    "sea",
    "railway",
    "railroad",
    "helmet",
    "ocean",
    "valley",
    "bridge",
  ]
