# metainfo for voc dataset
dataset: "voc"
data_root: "./datasets/VOCdevkit/VOC2012"
data_name_list: "./data/voc/val_id.txt"
name_to_cls_labels: "./data/voc/cls_labels.npy"
# we follow mmsegmentation to prepare dataset.
# so categories in pascal voc dataset are the same with mmsegmentation.
# related code: https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/datasets/voc.py
num_cls: 20 # not including background
category:
  plane: ["jet", "jetliner", "shuttle", "airplane", "plane", "aeroplane"]
  bicycle: ["bike", "bicycle"]
  bird:
    [
      "ostrich",
      "duck",
      "peacock",
      "bird",
      "seagull",
      "penguin",
      "swan",
      "owl",
      "flamingo",
      "eagle",
      "pelican",
      "emu",
      "pigeon",
      "chicken",
      "parrot",
    ]
  boat: ["ship", "kayak", "boat", "canoe", "sailboat"]
  bottle: ["bottle", "drink"]
  buses: ["buses", "bus", "tram"]
  car: ["cab", "taxi", "jeep", "cooper", "truck", "car", "wheel", "suv"]
  cat: ["lynx", "kitten", "cat"]
  chair: ["stool", "chair"]
  cow: ["bison", "cattle", "bull", "cow"]
  table: ["dining table", "diningtable", "table", "desk"]
  dog: ["dog", "puppy", "dachshund", "pug"]
  horse: ["pony", "horse"]
  motorbike: ["motorbike", "scooter"]
  people:
    [
      "they",
      "he",
      "skateboarder",
      "couple",
      "woman",
      "player",
      "she",
      "wrestler",
      "man",
      "him",
      "skier",
      "her",
      "chef",
      "girl",
      "boy",
      "parent",
      "person",
      "baby",
      "child",
      "groom",
      "bride",
      "people",
      "speaker",
    ]
  plant: ["potted plant", "pottedplant", "plant", "flower"]
  sheep: ["lamb", "goat", "sheep"]
  sofa: ["couch", "sofa"]
  train: ["train"]
  monitor: ["television", "tvmonitor", "screen", "tv", "monitor"]
bg_category:
  [
    "ground",
    "land",
    "grass",
    "tree",
    "building",
    "wall",
    "sky",
    "lake",
    "water",
    "river",
    "sea",
    "railway",
    "railroad",
    "keyboard",
    "helmet",
    "cloud",
    "house",
    "mountain",
    "ocean",
    "road",
    "rock",
    "street",
    "valley",
    "bridge",
    "sign",
  ]
