# config for voc12 dataset
dataset: "voc12"

# input/output/model paths
data_root: "./VOCdevkit/VOC2012"
data_name_list: "./data/voc12/val_id.txt"
output_path: "./output/classification/voc12"
clip_path: "/data2/wjl/sdsseg/open_vocabulary/clip-vit-large-patch14"
blip_path: "/data/wjl/ptp_diffusion/blip/blip-image-captioning-large"

# classification process settings (classification.py)
clip_device: "cuda:5"
blip_device: "cuda:5"
num_workers: 0
pin_mem: True
input_size: 224
enable_text_similarity: True
enable_text_and_image_similarity: True
enable_synonym_matching: True
train_interpolation: "bicubic"
text_threshold: 0.8
text_and_image_threshold: 0.97

# dataset metainfo
labels_synonym:
    {
        "plane": ["plane", "jet", "airplane", "jetliner", "shuttle"],
        "bicycle": ["bicycle", "bike"],
        "bird":
            [
                "bird",
                "seagull",
                "parrot",
                "owl",
                "pigeon",
                "flamingo",
                "emu",
                "penguin",
                "duck",
                "eagle",
                "ostrich",
                "chicken",
                "peacock",
                "pelican",
                "swan",
            ],
        "boat": ["boat", "sailboat", "ship", "kayak", "canoe"],
        "bottle": ["bottle", "drink"],
        "buses": ["bus", "tram"],
        "car":
            ["car", "suv", "wheel", "truck", "jeep", "cooper", "taxi", "cab"],
        "cat": ["cat", "kitten", "lynx"],
        "chair": ["chair", "stool"],
        "cow": ["cow", "bull", "bison", "cattle"],
        "table": ["table", "desk"],
        "dog": ["dog", "dachshund", "puppy", "pug"],
        "horse": ["horse", "pony"],
        "motorbike": ["motorbike", "scooter"],
        "people":
            [
                "person",
                "they",
                "he",
                "she",
                "him",
                "her",
                "man",
                "woman",
                "child",
                "baby",
                "skateboarder",
                "speaker",
                "boy",
                "girl",
                "bride",
                "groom",
                "parent",
                "couple",
                "player",
                "wrestler",
                "chef",
                "skier",
            ],
        "plant": ["plant", "pottedplant", "flower"],
        "sheep": ["sheep", "lamb", "goat"],
        "sofa": ["sofa"],
        "train": ["train"],
        "monitor": ["monitor", "screen", "television", "tv"],
    }
