# config for coco dataset
dataset: "coco"

# input/output/model paths
data_root: "./COCO2014"
data_name_list: "./data/coco_train_id.txt"
output_path: "./output/coco"
diffusion_path: "/data/wjl/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/c9ab35ff5f2c362e9e22fbafe278077e196057f0"
blip_path: "/data/wjl/ptp_diffusion/blip/blip-image-captioning-large"

# main process settings (main.py)
device: 4
seed: 4307
use_blip: True
print_prompt: False # 是否打印prompt
self_times: 1 # 乘以self_att的次数
self_64_times: 1 # 乘以self_64的次数
norm_bias: 0.4 # 标准化attention使用的bias
norm_factor: 8 # 标准化attention使用的factor

# ptp attention settings (ptp_utils.py)
target_factor: 0.5 # source img latent需要融合target img latent的比例
cross_weight: [0.3, 0.5, 0.1, 0.1] # [8, 16, 32, 64]解析度cross attention的权重

# dds loss settings (dds_utils.py)
use_dds: True
timesteps: [1, 25, 50, 75, 100, 125, 150]
guidance_scale: 7.5
lr: 1.0e-1
loss_factor: 2000.0
alpha_exp: 0.0
sigma_exp: 0.0

# dataset metainfo
category:
  [
    "person",
    "bicycle",
    "car",
    "motorbike",
    "aeroplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "sofa",
    "pottedplant",
    "bed",
    "diningtable",
    "toilet",
    "tvmonitor",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrus",
  ]
bg_category:
  [
    "ground",
    "land",
    "grass",
    "tree",
    "building",
    "wall",
    "sky",
    "lake",
    "water",
    "river",
    "sea",
    "railway",
    "railroad",
    "helmet",
    "cloud",
    "house",
    "mountain",
    "ocean",
    "road",
    "rock",
    "street",
    "valley",
    "bridge",
  ]
